doc: exceptions
ems-project/maintainers pull request #11
Opened 2020-11-03 10:28 UTC by theus77

Exception coding standard

2020-11-03 10:53 UTC, coppee approved these changes

2020-11-03 10:56 UTC, dameert requested changes

2020-11-03 10:56 UTC, dameert commented on doc/coding_standards.md
> +
```suggestion
When there is an unexpected exception, an exception that should never happened, like an exception throw in order to solve a phpstan issue, throw a ```\RuntimeException```. We should avoid using ```\Exception``` in order to simplify logs analysis.

```

2020-11-18 19:37 UTC, coppee approved these changes

2020-11-24 10:28 UTC, dameert commented
https://www.php.net/manual/fr/class.throwable.php

2020-11-24 10:30 UTC, IsaMic approved these changes

2020-11-24 11:41 UTC, dameert approved these changes

2020-11-24 12:09 UTC, Davidmattei approved these changes

2020-12-01 10:20 UTC, merged